[package]
name = "server"
version = "2.0.0"
authors = ["Chadtech"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.3"
actix-session = "0.4"
actix-utils = "2"
env_logger = "0.8"
actix-cors = "0.5.4"
notify = "4.0.15"
hex = "0.4.2"
shared = { path = "../shared" }
bincode = "1.0"
